# Generated by Django 5.1 on 2024-08-26 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teacher_gender_alter_teacher_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': "O'qituvchi", 'verbose_name_plural': "O'qituvchilar"},
        ),
    ]
