# Generated by Django 5.1 on 2024-08-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_course_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson_duration',
            options={'verbose_name': 'Dars davomiyligi', 'verbose_name_plural': 'Dars davomiyligi'},
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='57670', max_length=150, unique=True),
        ),
    ]
