# Generated by Django 5.1 on 2024-08-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='token_id',
            field=models.CharField(default='77477336', max_length=150, unique=True),
        ),
    ]
