# Generated by Django 5.1 on 2024-08-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_token_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='token_id',
            field=models.CharField(default='36900460', max_length=150, unique=True),
        ),
    ]
