# Generated by Django 5.1 on 2024-08-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_token_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='token_id',
            field=models.CharField(default='72729239', max_length=150, unique=True),
        ),
    ]
