# Generated by Django 5.1 on 2024-08-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_token_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='token_id',
            field=models.CharField(default='91155166', max_length=150, unique=True),
        ),
    ]
