# Generated by Django 5.1 on 2024-08-24 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0005_alter_course_course_code'),
        ('other', '0001_initial'),
        ('teacher', '0002_alter_teacher_gender_alter_teacher_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('days', models.CharField(choices=[('mon_wed_fri', 'Monday, Wednesday, Friday'), ('tue_thu_sat', 'Tuesday, Thursday, Saturday'), ('everyday', 'Everyday')], max_length=256)),
                ('time', models.TimeField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='other.room')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
    ]
