# Generated by Django 5.1 on 2024-08-26 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': 'Guruh', 'verbose_name_plural': 'Guruhlar'},
        ),
    ]
